theme: jekyll-theme-minimal
title:  Exploring Geographical Bias in Beer Ratings : "Is Your State Swaying Your Sip?"
description: The X0x0 team website for ADA
show_downloads: True
navigation:
  - title: Home
    url: README
  - title: Example
    url: /
  - title : Why selecting the US?
    url: USselection
